<?php

namespace AppBundle\Repository;

/**
 * BasketOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BasketOrderRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function getOrdersBetween($start,$end)
    {
        $qb = $this->createQueryBuilder('p')
                    ->where('p.delivery_time BETWEEN :start AND :end');
        $qb->setParameter(':start', $start);
        $qb->setParameter(':end', $end);
        return $qb->getQuery()->getResult();
        
    }
    
}
