<?php

namespace AppBundle\Repository;

/**
 * BasketOrderContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BasketOrderContentRepository extends \Doctrine\ORM\EntityRepository
{
}
