<?php

namespace AppBundle\Repository;

/**
 * BasketCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BasketCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
