<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Basket;

/**
 * BasketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BasketRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function getAllBasketWithProductList()
    {
         $qb = $this->createQueryBuilder('b')
                    ->leftJoin('b.category ', "cate")
                    ->addSelect('cate')
                    ->leftJoin('b.product_list ', "product")
                    ->addSelect('product');
        return $qb->getQuery()->getArrayResult();
    }
    
    public function findByCategoryId($id_category) {
    	$query = $this->getEntityManager()
    		->createQuery("SELECT b FROM AppBundle:Basket b JOIN b.category c WHERE c.id = :id_category")
    		->setParameter("id_category", $id_category);
    	return $query->getResult();
    }
}
