<?php

namespace AppBundle\Repository;

/**
 * BasketContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BasketContentRepository extends \Doctrine\ORM\EntityRepository
{
}
