<?php

namespace AppBundle\Repository;

/**
 * BasketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BasketRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function getAllBasketWithProductList()
    {
         $qb = $this->createQueryBuilder('b')
                    ->leftJoin('b.category ', "cate")
                    ->addSelect('cate')
                    ->leftJoin('b.product_list ', "product")
                    ->addSelect('product');
        return $qb->getQuery()->getArrayResult();
    }
}
