<?php

namespace AppBundle\Repository;

/**
 * DeliveryPromiseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeliveryPromiseRepository extends \Doctrine\ORM\EntityRepository
{
}
