<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository {
	
	public function getProductByCompany($company) {
		
		$categoryIds = array();
		for($i = 0; $i < count($company->getCategories()); $i++) {
			array_push($categoryIds, $company->getCategories()[$i]->getId());
		}
			
		$products = $this->getEntityManager()->getRepository("AppBundle:Product")->findAll();
		
		$shameProducts = array();
		for($i = 0; $i < count($products); $i++) {
			if(in_array($products[$i]->getCategory()->getId(), $categoryIds)) {
				array_push($shameProducts, $products[$i]);
			}
		}
		
		return $shameProducts;
		
	}
	
}
