<?php

namespace AppBundle\Repository;

/**
 * StockPromiseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockPromiseRepository extends \Doctrine\ORM\EntityRepository
{
}
