<?php

namespace AppBundle\Repository;

/**
 * StockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockRepository extends \Doctrine\ORM\EntityRepository
{
    
    
    
    public function findCurrentStockFor($product_id)
    {
        $qb = $this->createQueryBuilder('s')
                    ->where("s.product = ".$product_id);
                   
        return $qb->getQuery()->getArrayResult();    
    }
    
}
