<?php

namespace AppBundle\Repository;

/**
 * StockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockRepository extends \Doctrine\ORM\EntityRepository
{
    
    
    
    public function findCurrentStockFor($product_id)
    {
        $qb = $this->createQueryBuilder('s')
                    ->where("s.product = :product_id order by s.id desc");
        $qb->setParameter("product_id", $product_id);
        $qb->setMaxResults(1);
        $stocks = $qb->getQuery()->getResult();
        if(!is_null($stocks)) {
	        return $stocks[0];
        } else {
        	return null;
        }
    }
    
}
