security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            logout:       true
            anonymous:    true

    access_control:
 #       - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
 #       - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
 #       - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/basket$, role: ROLE_USER }
        - { path: ^/basket_category$, role : ROLE_USER }
        - { path: ^/product$, role : ROLE_USER }
        - { path: ^/category$, role : ROLE_USER }
        - { path: ^/stock$, role : ROLE_USER }
        - { path: ^/stats$, role : ROLE_USER }