security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER,ROLE_FOURNISSEUR]
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        auth_token_user_provider:
            id: auth_token_user_provider

    firewalls:
    
        secured-api:
            pattern: ^/api/
            stateless: true
            simple_preauth:
                authenticator: auth_token_authenticator
            provider: auth_token_user_provider
            anonymous: ~
            
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            logout:       true
            anonymous:    true

    access_control:
 #       - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
 #       - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
 #       - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/basket$, role: ROLE_ADMIN }
        - { path: ^/basket_category$, role : ROLE_ADMIN }
        - { path: ^/product$, role : ROLE_ADMIN }
        - { path: ^/category$, role : ROLE_ADMIN }
        - { path: ^/stock$, role : ROLE_ADMIN }
        - { path: ^/stats$, role : ROLE_ADMIN }
        - { path: ^/orders$, role : ROLE_ADMIN }
        - { path: ^/company$, role : ROLE_ADMIN }